# Generated by Django 4.1.7 on 2023-03-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.IntegerField(primary_key='true', serialize=False, verbose_name='task_id')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('deadline', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
